import { ThemeColors } from '@theme/constants';
import { StyleSheet } from 'react-native';
const styles = (Colors: ThemeColors) =>
  StyleSheet.create({
    wrapper: { marginBottom: 8 },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      width: '100%',
      paddingHorizontal: 15,
      paddingVertical: 16,
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: Colors.border,
      backgroundColor: Colors.background + '5',
    },
    rowClosed: { borderRadius: 8 },
    incomeBadge: { backgroundColor: '#064e3b' },
    purchaseBadge: { backgroundColor: '#1e40af' },
    typeText: { color: '#a7f3d0', fontWeight: '600', fontSize: 12 },
    /* PROPERTY */ propertyContainer: { width: '30%' },
    propertyTitle: {
      color: Colors.textPrimary,
      width: '100%',
      fontSize: 15,
      fontWeight: '600',
    },
    tokenText: { color: '#9ca3af', fontSize: 12, marginTop: 2 },
    /* AMOUNT */ amount: {
      width: '30%',
      textAlign: 'right',
      fontWeight: '600',
    },
    incomeAmount: { color: Colors.success },
    purchaseAmount: { color: Colors.textSecondary },
    /* DATE */ date: {
      width: 110,
      textAlign: 'right',
      color: Colors.textMuted,
    },
    /* STATUS */ statusBadge: {
      marginLeft: 12,
      backgroundColor: '#84cc16',
      paddingHorizontal: 14,
      paddingVertical: 6,
      borderRadius: 999,
    },
    statusText: { color: '#052e16', fontWeight: '700', fontSize: 12 },
    /* CHEVRON */ chevronIcon: {
      marginLeft: 8,
      fontSize: 16,
      color: Colors.textMuted,
      lineHeight: 18,
    },
    chevronOpen: { transform: [{ rotate: '180deg' }] },
    detailsContainer: {
      borderWidth: 1,
      borderTopWidth: 0,
      borderColor: Colors.border,
      borderBottomLeftRadius: 8,
      borderBottomRightRadius: 8,
      backgroundColor: Colors.background,
      paddingHorizontal: 16,
      paddingVertical: 12,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'flex-start',
      paddingVertical: 4,
    },
    detailLabel: { fontSize: 12, color: Colors.textMuted, fontWeight: '500' },
    detailValue: {
      fontSize: 12,
      color: Colors.textPrimary,
      fontWeight: '600',
      width: '70%',
      textAlign: 'right',
    },
  });
export default styles;
