export enum ROUTES {
  HOME = 'Home',
  PORTFOLIO = 'Portfolio',
  MARKETPLACE = 'Marketplace',
  TABS = 'Tabs',
  PROPERTY_DETAILS = 'PropertyDetails',
  KYC = 'KycScreen',
  NOTIFICATIONS = 'Notifications',
  WALLET = 'WalletScreen',
  CREATE_NFT = 'CreateNft',
  LISTED_PROPERTIES = 'ListedProperties',
  INVESTED_PROPERTIES = 'InvestedProperties',
  TRANSACTIONS = 'Transactions',
  OWNED_PROPERTY = 'UserOwnedProperty',
}
